# Generated by Django 6.0 on 2025-12-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('department', models.CharField(help_text='e.g. Operations, Marketing', max_length=100)),
                ('location', models.CharField(default='Ruiru, Kenya', max_length=100)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-Time', max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(help_text='The date applications close')),
                ('description', models.TextField(help_text='Main job summary.')),
                ('meta_description', models.TextField(blank=True, help_text='SEO description (150 chars)')),
                ('responsibilities', models.TextField(help_text='Enter each point on a new line.')),
                ('requirements', models.TextField(help_text='Enter each point on a new line.')),
                ('benefits', models.TextField(help_text='Enter each point on a new line.')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
