# Generated by Django 6.0 on 2025-12-21 08:33

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'John Kamau' or 'Free Site Visits' (Max 50 chars)", max_length=50)),
                ('item_type', models.CharField(choices=[('team', 'Team'), ('poster', 'Events/Poster'), ('property', 'Property (Manual)')], default='team', max_length=20, verbose_name='Category')),
                ('image', models.ImageField(help_text='Upload an image (Max Size: 1MB)', upload_to='gallery/', validators=[gallery.models.validate_image_size])),
                ('description', models.CharField(help_text="e.g. 'Senior Sales Manager guiding a client.' (Max 100 chars)", max_length=100, verbose_name='Short Description')),
                ('alt_text', models.CharField(blank=True, help_text='Auto-generated from Title if left empty. Describes image for Google.', max_length=255, verbose_name='SEO Alt Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'ordering': ['-created_at'],
            },
        ),
    ]
