# Generated by Django 6.0 on 2026-02-08 20:23

import cloudinary.models
import gallery.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Upload an image (Max Size: 1MB)', max_length=255, validators=[gallery.models.validate_image_size], verbose_name='Gallery Image'),
        ),
    ]
