# Generated by Django 6.0 on 2025-12-21 08:33

import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kithyoko, Machakos', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title if left empty', unique=True)),
                ('size', models.CharField(help_text='e.g. 50x100 or 1 Acre', max_length=50)),
                ('price', models.PositiveIntegerField(help_text='Enter numbers only. Commas are added automatically on the site.')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out'), ('Coming Soon', 'Coming Soon')], default='Available', max_length=20)),
                ('image', models.ImageField(help_text='Max size 1MB. This will be the main display image.', upload_to='properties/main/', validators=[properties.models.validate_image_size], verbose_name='Cover Image')),
                ('description', models.TextField()),
                ('meta_description', models.TextField(blank=True, help_text='Auto-generated from description, but you can edit it.')),
                ('map_src', models.TextField(blank=True, help_text='Paste the full Google Maps Embed <iframe...> code.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.location')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Water on Site', max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_list', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Max size 1MB.', upload_to='properties/gallery/', validators=[properties.models.validate_image_size])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'More Property Images',
            },
        ),
    ]
