# Generated by Django 6.0 on 2025-12-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Royal Gardens - Kithyoko', max_length=200)),
                ('location', models.CharField(help_text='e.g. Machakos, Ruiru', max_length=100)),
                ('price', models.CharField(help_text='e.g. Ksh 150,000', max_length=50)),
                ('size', models.CharField(help_text='e.g. 50x100', max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold Out'), ('Reserved', 'Reserved')], default='Available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
