# Generated by Django 6.0 on 2026-02-08 20:17

import cloudinary.models
import properties.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Max size 1MB. This will be the main display image.', max_length=255, validators=[properties.models.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Max size 1MB.', max_length=255, validators=[properties.models.validate_image_size], verbose_name='image'),
        ),
    ]
