# Generated by Django 6.0 on 2025-12-17 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.TextField(default='', help_text='Separate features with commas (e.g. Water, Electricity, Fenced)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='map_src',
            field=models.TextField(blank=True, help_text='Google Maps Embed Link'),
        ),
        migrations.AddField(
            model_name='property',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description for Google results'),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title if left empty', unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='properties/main/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(help_text='e.g. 130,000', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.CharField(help_text='e.g. 50x100 or 1 Acre', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out'), ('Coming Soon', 'Coming Soon')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.property')),
            ],
        ),
    ]
