# Generated by Django 6.0 on 2025-12-17 14:53

import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_features_property_map_src_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kithyoko, Machakos', max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'More Property Image', 'verbose_name_plural': 'More Property Images'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(help_text='Max size 1MB. This will be the main display image.', upload_to='properties/main/', validators=[properties.models.validate_image_size], verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Auto-generated from description, but you can edit it.'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/gallery/', validators=[properties.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.location'),
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Water on Site', max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_list', to='properties.property')),
            ],
        ),
    ]
