# Generated by Django 6.0 on 2026-02-08 20:23

import cloudinary.models
import properties.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Max size 1MB. This will be the main display image.', max_length=255, validators=[properties.models.validate_image_size], verbose_name='Cover Image'),
        ),
    ]
