# Generated by Django 6.0 on 2025-12-17 16:17

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_location_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'More Property Images'},
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Max size 1MB. This will be the main display image.', null=True, upload_to='properties/main/', validators=[properties.models.validate_image_size], verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(help_text='Max size 1MB.', upload_to='properties/gallery/', validators=[properties.models.validate_image_size]),
        ),
    ]
