# Generated by Django 6.0 on 2025-12-17 16:23

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertyimage_options_alter_property_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='properties/main/default.jpg', help_text='Max size 1MB. This will be the main display image.', upload_to='properties/main/', validators=[properties.models.validate_image_size], verbose_name='Cover Image'),
            preserve_default=False,
        ),
    ]
