# Generated by Django 6.0 on 2025-12-21 08:33

import blog.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title if left empty', unique=True)),
                ('post_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video')], default='article', max_length=10, verbose_name='Type')),
                ('image', models.ImageField(blank=True, help_text='Max size 1MB. Required for Articles.', null=True, upload_to='blogs/covers/', validators=[blog.models.validate_image_size], verbose_name='Cover Image')),
                ('description', models.TextField(help_text='Used for the card summary.', verbose_name='Short Description')),
                ('meta_description', models.TextField(blank=True, help_text='Auto-generated from description if empty.')),
                ('video_url', models.URLField(blank=True, help_text='e.g. https://www.youtube.com/embed/...', null=True, verbose_name='Video Embed URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Article Content')),
                ('date_published', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Select a category from the list.', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date_published'],
            },
        ),
    ]
