# Generated by Django 6.0 on 2026-02-08 20:17

import blog.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Max size 1MB. Required for Articles.', max_length=255, null=True, validators=[blog.models.validate_image_size], verbose_name='Cover Image'),
        ),
    ]
