# Generated by Django 6.0 on 2025-12-21 08:33

import testimonials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, help_text='Check this box and hit save to make the review visible on the website.')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Investor', 'Investor'), ('Home Owner', 'Home Owner'), ('Diaspora Client', 'Diaspora Client'), ('Business Owner', 'Business Owner'), ('Partner', 'Partner')], default='Investor', max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=300)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('title_number_used', models.CharField(help_text='The serial number provided by the client.', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[testimonials.validators.validate_file_size, testimonials.validators.validate_image_extension, testimonials.validators.validate_real_image])),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='ValidSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Enter the Title Deed/Plot Number (e.g. FEDHA-001)', max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='System checks this automatically when a review is submitted.')),
            ],
            options={
                'verbose_name': 'Valid Title Number',
            },
        ),
    ]
