# Generated by Django 6.0 on 2026-02-08 20:17

import cloudinary.models
import testimonials.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Client photo (Optional). Max 1MB.', max_length=255, null=True, validators=[testimonials.validators.validate_file_size, testimonials.validators.validate_image_extension, testimonials.validators.validate_real_image], verbose_name='image'),
        ),
    ]
